### ISSUE TITLE
Missing /etc/localtime

### ISSUE THREAD

**Issue by jappa** [singularityhub/singularity-docker#11]
I am using v3.6.1 from quay.io/singularity/singularity but it looks like the base alpine linux is missing /etc/localtime. When I try to run the inspect command I get the following error
FATAL:   container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: mount source /etc/localtime doesn’t exist
Is there a quick fix or can the docker image be recreated with the missing file?

**Comment by vsoch** [comment]
Let me try a local build and see if I can fix it, and if so, I can update the recipe. Can you give me the command to reproduce your issue for the current build?

**Comment by vsoch** [comment]
okay, well I'll leave it to you to test then! Please try quay.io/singularity/singularity:3.6.1-rc2 and let me know if it works - if so, I'll update the recipes for the automated build (for both regular and slim versions).

**Comment by jappa** [comment]
That fix works. The command to reproduce the issue is to inspect an image file.  Thanks for the quick fix.

**Comment by jappa** [comment]
Here is the reproducer cmd 
docker run -it --rm --privileged -v `pwd`:/tmp/local/ quay.io/singularity/singularity:3.6.1 inspect /tmp/local/image.sif

**Comment by vsoch** [comment]
Great! Give me a few minutes and I'll update the automated builds.

**Comment by vsoch** [comment]
okay containers are pushed, and the temporary testing image is removed. Thanks for reporting the issue!
