### ISSUE TITLE
base container update

### ISSUE THREAD

**Issue by tsnowlan** [singularityhub/singularity-docker#14]
This is a really handy repo, but the underlying golang/alpine image is getting pretty old. _e.g.,_ docker is 18.09.8 unless `/etc/apk/repositories` is manually updated.

Updating to the current `1.16.6-alpine` would be ideal. Thanks!

**Comment by vsoch** [comment]
Definitely can do for the next version update. Thanks!

**Comment by vsoch** [comment]
This should be all set! https://quay.io/repository/singularity/singularity/manifest/sha256:1c078d955856fad1af3688211c66d2595df8f3858f0269742b179ad5fa4ab79f It's currently done for 3.8.1 as I was testing adding arm, and I'll do an update for 3.8.2 when that is confirmed to look good.
