### ISSUE TITLE
gitlab-3.1-slim

### ISSUE THREAD

**Issue by scholtalbers** [singularityhub/singularity-docker#4]
Thanks for the provided images and gitlab integration examples. 
I created a fork and new branch for 3.1 with a working gitlab version at https://github.com/scholtalbers/singularity-docker/tree/gitlab-3.1-slim
Also created a custom version of your `.gitlab-ci.yml` version to work with this image at https://github.com/scholtalbers/singularity-gifascii 

Feel free to merge/fork/comment/....

**Comment by vsoch** [comment]
If you think this would be useful to others, I'd be happy to make a `gitlab-3.1-slim` branch for you to PR to. It's just 3.1 slim without the entrypoint, which could be helpful to someone.

**Comment by vsoch** [comment]
https://github.com/singularityhub/singularity-docker/tree/gitlab-3.1-slim

**Comment by scholtalbers** [comment]
👍thanks
