### ISSUE TITLE
Need for authentification when building a singularity image from private docker image

### ISSUE THREAD

**Issue by Trophime** [singularityhub/singularity-docker#8]
Hi, I would like to use docker singularity to build images for some machines requiring old version of singularity.

The trouble is that I would like to build from a private docker repo
So I need authentification...

How to pass `SINGULARITY_DOCKER_USERNAME` and `SINGULARITY_DOCKER_PASSWORD` to singularity when running with docker?

What is the best way to proceed?

Actually I've tried to build a custom singularity image like that:
```
FROM singularityware/singularity:2.4

ARG DOCKER_USER="barbu"
ARG DOCKER_PASSWD="barbu"

# Set credentials for singularity
ENV SINGULARITY_DOCKER_USERNAME=${DOCKER_USER}
ENV SINGULARITY_DOCKER_PASSWORD=${DOCKER_PASSWD}
```
But when I run:
```
docker run --privileged -t --rm -v :/tmp/x mysingularity:2.4  build /tmp/x/x.simg /tmp/x/docker.def
```
I've got an error message like that:
```
Singularity: image-type (U=0,P=24)> Unknown image format/type: /tmp/x/docker.def

Singularity: image-type (U=0,P=24)> Retval = 255

Using container recipe deffile: /tmp/x/docker.def
Sanitizing environment
ESC[0mAdding base Singularity environment to container
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/import.py", line 109, in <module>
    main()
  File "/usr/local/libexec/singularity/python/import.py", line 86, in main
...
```

I shall have missed something...
Any idea?

Best
C

**Comment by vsoch** [comment]
I think you can just provide them in the environment at runtime, and this would be a better approach than building into a container. Try:

```bash
$ docker run --privileged -t --rm -v $PWD:/tmp/x \
                    --env SINGULARITY_DOCKER_USERNAME=${DOCKER_USER} \
                    --env SINGULARITY_DOCKER_PASS=${DOCKER_PASS} \
                    singularityware/singularity:2.4  build /tmp/x/x.simg /tmp/x/docker.def
```

I would first verify that the variables are being passed, for example:

```bash
$ docker run --env SINGULARITY_DOCKER_USER=pancakes --env SINGULARITY_DOCKER_PASSWORD=passy --entrypoint env singularityware/singularity:2.4   | grep DOCKER
SINGULARITY_DOCKER_USER=pancakes
SINGULARITY_DOCKER_PASSWORD=passy
```
And finally, if there are strange errors, please share here, and I think we would also want to look back in deprecated docs to see if there was support for this then (along with build).

**Comment by vsoch** [comment]
I'm going back to sleep, but I'll be back in a few hours :)

**Comment by vsoch** [comment]
Let me know if this works for you.

**Comment by Trophime** [comment]
it works. Thank for you hint ;)

**Comment by vsoch** [comment]
Sure thing! Closing issue.
