### ISSUE TITLE
Singularity 3.3.0 containers are missing newuidmap

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-docker#9]
To use `--fakeroot` you need `newuidmap` which is in package `shadow-uidmap`. Install that to the final container to make it work.

**Comment by vsoch** [comment]
Thanks @Flamefire , will do this now.

**Comment by vsoch** [comment]
okay just updated:

 - latest (the slim version)
 - v3.3.0-slim
 - v3.3.0 

to all have shadow-uidmap. Please give it a test if you are able.

**Comment by Flamefire** [comment]
Just found out, that those are not really required, only when it is installed in non-setuid-mode which is not the case here. Sorry for the noise

**Comment by vsoch** [comment]
No worries @Flamefire, it doesn't hurt to add. :)
